### ISSUE TITLE
Tab view always has the height equal to height of the highest tab

### ISSUE THREAD

**Issue by you-fail-me** [happypancake/react-native-scrollable-tab-view#415]
How can I make it adopt active tab's height?

**Comment by skv-headless** [comment]
I don't understand. Please provide more information. Pictures are very useful

**Comment by vscholz** [comment]
@skv-headless Let's say the first tab has a height of 200px and the second one has a height of 1000px. As a result every tab will have the height of 1000px.

**Comment by you-fail-me** [comment]
@skv-headless yes, @vscholz is right. sorry for the delay(

**Comment by roscioli** [comment]
Has anybody found any fixes for this?

**Comment by denizs** [comment]
Anyone?

**Comment by denizs** [comment]
Ok here's how I did it. It's a hot fix, but I'll revisit this topic on a later stage and make a PR as I'm in a hurry right now. So let's dive into it:

I made use of the `onChangeTab` callback, that is already provided out of the box. 
The callback function takes an object which has the current slide's `ref`, which is equal to the `tabLabel` prop and will fire whenever a tab is changed. **Yaay!**

## 1st 
Set your Tab Components `ref` names respectively to your `tabLabel`s like so:

```javascript

<View ref='someTabName' tabLabel="someTabName" />

```

## 2nd

We want to apply the calculated height to our SrollableTabView. As the style prop is already  passed to the relevant component, we can simply keep a style object in our parent component's state and pass it to our TabView:

```javascript
//constructor
constructor(props){
    super(props)
    this.state ={
      tabViewStyle:{
       // Some style you don't care for just to init something
        backgroundColor:'transparent'
      },
     // I'll explain that in a bit
      firstTabSwitch: true
    }
  }
// Component:

<ScrollableTabView
           onChangeTab={(obj) => this._handleTabHeight(obj)}
           style={this.state.tabViewStyle}
           prerenderingSiblingsNumber={0} 
          {{...other}}  />

```

**A few things to note here:**

On init, we don't pass any height to our style in order to let the TabView expand to the it's initial view's height rather than manually setting the height on mount. On the other hand, this means we have to stop our other - maybe larger views - from rendering. We achieve this by setting `prerenderingSiblingsNumber={0}`. Result: Our ScrollableTabView renders with the height of the initial view. As we haven't set any height yet, it won't depend whether your second tab is shorter or taller - it will adapt to the height of the current view. 

**HOWEVER**: We have set the prop `prerenderingSiblingsNumber={0}` meaning, that on first tab change, the new view will have a height of 0, causing the TabView to collapse. That's what the `firstTabSwitch`is for. We'll use this to prevent our callback function to set the height to 0 on first render.

## Lastly

Ok let's write our callback function. As we already defined our `ref`s, we can now access the `height` like so:

```javascript

_handleTabHeight(obj){
    this.refs[obj.ref.props.tabLabel].measure(this._setTabHeight.bind(this))
  }

  _setTabHeight(ox, oy, width, height, px, py) {
    if(!this.state.firstTabSwitch){
      this.setState({tabViewStyle: {height: height}})
    } else{
      this.setState({firstTabSwitch:false})
    }
  }

```

Oddly, you can't simply call measure on `obj.ref` but then who cares - 10 minute fix 💯 
Hope that helps :)

**Comment by mxmtsk** [comment]
@denizs your fix works well (thanks) except that if I keep switching between the tabs the height get's smaller and smaller up the point where everything is gone. :(

**Comment by Kowaio** [comment]
Up this issue.

I tried the proposed solution but it seems the `onLayout` measurements in those sub views still return the height of the highest tab.

**Comment by sospedra** [comment]
My solution is using `ScrollView`s.

```js
<ScrollableTabView style={{ height: Dimensions.get('window').height }}>
  <ScrollView>
    <View style={{ height: 300, backgroundColor: 'cadetblue' }} />
  </ScrollView>

  <SrcollView>
    <View style={{ height: 5000, backgroundColor: 'lightgreen' }} />
  </ScrollView>
</ScrollableTabView>
```

**Comment by Kowaio** [comment]
Hello @sospedra,
Thanks for your answer. I tried with `ScrollView` instead of `View` but it didn't changed much since the content of those tabs is dynamic. Therefore I can't set a fixed height as in your example. And like I said above, even when adding `onLayout` measurement of those inner views, the `ScrollableTableView` will keep the highest height of its siblings.

**Comment by sospedra** [comment]
Hey @Kowaio ,

The fixed height is fot the container, aka the `ScrollableTabView`. Not the tabs, aka the `ScrollView`. I don't know how's your code but it'll be -- probably -- more than just replace `View` by the scrollable version.

Mayebe if you post a rnplay.org example I could help you better ;)

**Comment by Kowaio** [comment]
Thanks again @sospedra.
Yeah sorry, I was talking about your `height` in your `Views` content.

About setting a fixed height for the `ScrollableTabView`, it's unfortunately impossible since this `ScrollableTabView` is itself inside a `ScrollView`.

Here's a draft of my current code: http://www.heypasteit.com/clip/3ASU

**Comment by denizs** [comment]
Ok so I dug into this issue a little bit:
My approach was to use the `onLayout` and `onChangeTab` event of every scene component to calculate the height of the displayed scene and change the contentContainerStyle respectively on every swipe. However, it seems that the `StaticContainer` Component used in `SceneComponent.js` is causing the container to take the full height of the parent container resulting in a missing `onLayout` event, as long as one tab does not exceed the current tab view's height (hence the height of the tallest component). @skv-headless is there any good reason to stick to StaticContainer? Otherwise I would start working on a fix for that. I found that replacing the `StaticContainer` with a `View` component works fine regarding the `onLayout`event.
Best,
D

**Comment by Lxxyx** [comment]
Solved by use @denizs method.

But use setTimeout(fn, 1) to ensure get correct height.

**Comment by denizs** [comment]
Awesome @Lxxyx!

**Comment by eduduardo** [comment]
There will be any fix on the package or the only fix is with the @denizs 's hotfix ?

**Comment by skv-headless** [comment]
If you have problems with `StaticContainer` you can try `prerenderingSiblingsNumber={Infinity}`.

**Comment by sankalpsingha** [comment]
Anyone? Is there an official method of doing this? Can this be implemented as a feature?

**Comment by laclys** [comment]
main.js
```javascript
  _handleTabHeight(obj){
    console.log(this.refs[obj.ref.props.tabLabel].state.name)
    this.refs[obj.ref.props.tabLabel].gogogo((x,y,w,h,l,t) => {
      if(h!==0){
        this.setState({tabViewStyle: {height: h}})
      }
    })
  }
```
```javascript
        <ScrollableTabView
           onChangeTab={(obj) => this._handleTabHeight(obj)}
           style={this.state.tabViewStyle}
        >
            <ReactPage ref='high1' tabLabel="high1" />
            <ReactPage2 ref='high2' tabLabel="high2" />
            <ReactPage3 ref='high3' tabLabel="high3" />
        </ScrollableTabView>
```

ReactPage.js/ReactPage2.js/ReactPage3.js
```javascript
  gogogo(cb) {
      this.refs.test.measure(cb)
  }
  render() {
    return (
      <View
        ref='test'
        style={{
          height: 300,
          backgroundColor: 'blue'
        }}
      >
      </View>
    );
  }
}
```
worked~!

**Comment by aijason** [comment]
Why didn't this issue come up with a new solution

**Comment by zhouyingkai1** [comment]
+1

**Comment by Hiro5409** [comment]
+1

**Comment by rayray-py** [comment]
+1

**Comment by RobertOConnorMM** [comment]
+5

**Comment by chris-bytelion** [comment]
Still waiting

**Comment by chulinyin** [comment]
@laclys Thanks, your method really works. In addition,  when you apply tabViewStyle's height to ScrollableTabView' style, you should **plus tabBar's height**. And in my practice, you can apply it to contentProps directly. like the following code:
```
<ScrollableTabView
  contentProps={{style:{...tabViewStyle}}}
>
</ScrollableTabView>
```

**Comment by dracudakid** [comment]
+1

**Comment by hashamhabib** [comment]
+1

**Comment by jeffzing** [comment]
set tabView height not works fine when subview contain flatlist, even though I creat a timeout for 2 sec，still can not get the flatlist's layout H. weird，and I don't know how to solve this problem, and now my situation is one of the subview height far beyond the short one. ugly page.

**Comment by StevenT1** [comment]
I found a solution that is not a good solution, but the effect can be achieved.
Referring to this method @denizs @laclys  ，  improvements were made by
me,The code is as follows:
`this.state={ LTabSwitch:true, 
        RTabSwitch:true, 
        Lheight:null,
        Rheight:null,」`
`_handleTabHeight(obj){
         this.refs.totop.scrollTo({x:0,y: 0,animated:true});
        this.refs[obj.ref.props.tabLabel].measure(this._setTabHeight.bind(this));
        this.LrState= obj.ref.props.tabLabel;
    }`
` _setTabHeight(ox, oy, width, height, px, py) {
        if(height!=0){
            if(this.state.firstTabSwitch) {
                if(this.LrState == 'Left' && this.state.LTabSwitch){
                    this.setState((prevState, props) => ({Lheight: height,
                        LTabSwitch:false}));
                }else if(this.LrState == 'Right' && this.state.RTabSwitch){
                    this.setState((prevState, props) => ({ Rheight: height,
                        RTabSwitch:false}));
                }
                if(this.LrState == 'Left')
                    this.setState((prevState, props) => ({tabViewStyle:{height: this.state.Lheight}}));
                else
                    this.setState((prevState, props) => ({tabViewStyle:{height: this.state.Rheight}}));
            }
        }
    }`

**Comment by StevenT1** [comment]
I found a solution that is not a good solution, but the effect can be achieved.
Referring to this method @denizs @laclys ， improvements were made by
me,The code is as follows:
```
this.state={ LTabSwitch:true,
 RTabSwitch:true, 
Lheight:null, 
Rheight:null,}
_handleTabHeight(obj){ 
this.refs.totop.scrollTo({x:0,y: 0,animated:true}); this.refs[obj.ref.props.tabLabel].measure(this._setTabHeight.bind(this)); 
this.LrState= obj.ref.props.tabLabel;
 }
_setTabHeight(ox, oy, width, height, px, py) {
 if(height!=0){
if(this.state.firstTabSwitch) {
 if(this.LrState == 'Left' && this.state.LTabSwitch){
 this.setState((prevState, props) => ({Lheight: height, LTabSwitch:false})); }
else if(this.LrState == 'Right' && this.state.RTabSwitch){ 
this.setState((prevState, props) => ({ Rheight: height, RTabSwitch:false})); }
 if(this.LrState == 'Left') 
this.setState((prevState, props) => ({tabViewStyle:{height: this.state.Lheight}})); 
else 
this.setState((prevState, props) => ({tabViewStyle:{height: this.state.Rheight}})); 
} 
} 
}
```

**Comment by ptomasroos** [comment]
@zcmgyu there is no repo provided with the issue

**Comment by andyr6381** [comment]
Hi, could anyone share source code of the above solution working, I've not been able to get it working on RN 57.8

**Comment by alexpchin** [comment]
I'm just adding a comment to this... I'm not 100% sure if I'm correct but I believe this might solve your problem?

```js
<ScrollableTabView style={{ flex: 1 }}>
  <FlatList tabLabel="First" contentContainerStyle={{ flexGrow: 1 }} /> // Could be inside a named component...
  <FlatList tabLabel="Second" contentContainerStyle={{ flexGrow: 1 }} /> // Could be inside a named component...
</ScrollableTabView>
```

**Comment by Cookizza** [comment]
Today marks 3 years of this issue in React Native.

You'd think it would be solvable without needing to add event listeners and calculate heights based on screen sizes.

Is there any solutions available to us today that wasn't possible in 2016?

**Comment by LeonardodeLima** [comment]
+1

**Comment by basilaiman** [comment]
2 years and +1

**Comment by ptomasroos** [comment]
Feel free to send a fix @basilaiman

**Comment by james-huang-git** [comment]
This was a solution that worked for me, it was important to have prerenderingSiblingsNumber if you display large amounts of content. Creating a state for each tabLabel allows you to define the height when needed.

``` javascript
  handleChangeTab(x) {
    this[x.ref.props.tabLabel].measure((ox, oy, width, height, px, py, label) => {
      if (this.state.tabHeight > height) {
        this.setState({ tabHeight: height })
      } else if (this.state.tabHeight < height) {
        if (this.state[x.ref.props.tabLabel]) {
          this.setState({ tabHeight: height });
        } else {
          this.setState({ tabHeight: undefined })
        }
      } else if (height !== 0) {
        this.setState({ tabHeight: height })
      }
      if (this.state[x.ref.props.tabLabel] === undefined) {
        this.setState({ [x.ref.props.tabLabel]: true });
      }
    })
  }

  render() {
    const { tabContent = data } = this.props;
    return (
        <ScrollableTabView
          onChangeTab={(x) => setTimeout(() => this.handleChangeTab(x), 100)}
          contentProps={{ style: { height: this.state.tabHeight }}}
          style={[this.props.tabViewStyle, {}]}
          initialPage={1}
          prerenderingSiblingsNumber={Infinity}
          renderTabBar={() => <ScrollableTabBar />}
        >
          {this.tabViewContent(tabContent)}
        </ScrollableTabView>
    );
  }
```

**Comment by pragupnewzera** [comment]
Try something like this, 
Fix the height of the parent widget to the maximum screen height you want that Tab Navigator to have.

    <ListView or ScrollView>
     <View style={{height:  (width)/(0.8)}} >
        <Tab.Navigator tabBar={(props) => <TabBar {...props} />}>
          <Tab.Screen name="T1" component={T1} />
          <Tab.Screen name="T2" component={T2} />
          <Tab.Screen name="T3" component={T3} />
        </Tab.Navigator>
       </View>
    </ ListView or ScrollView>


And for tabs do Something like this

T1 ->

    <View style={styles.container}>
      <ScrollView nestedScrollEnabled={true}>
        <FlatList
          numColumns={3}
          data={allMedia}
          keyExtractor={(item) => item.id}
          listKey={(post) => `${post.id}D`}
          renderItem={({ item }) => (Anything)}
          scrollEnabled ={false}
        />
      </ScrollView>
    </View>
    
Remember to disable the scroll view Inside the FlatList of tabs and wrap with a ScrollView with nestedScrollEnabled={true}
