### ISSUE TITLE
Any ideas on "how" to support infinite Scrolling?

### ISSUE THREAD

**Issue by qbig** [happypancake/react-native-scrollable-tab-view#44]
Any enlightenment ? I could have a few dozen tabs. How to render efficiently or do some sort of recycling ?

**Comment by brentvatne** [comment]
You might be able to use a ListView instead of a ViewPager and set horizontal scrolling and use [RecyclerViewBackedScrollView](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/recyclerview/RecyclerViewBackedScrollView.java) as the ListView's scroll component.

**Comment by ptomasroos** [comment]
Closing as this issue is very old, feel free to open a new issue if its still happening in the latest release
