### ISSUE TITLE
Do not support Android?

### ISSUE THREAD

**Issue by 594904020** [happypancake/react-native-scrollable-tab-view#785]
Do not support Android? Why can't Android display normally, IOS is normal?

**Comment by skicson** [comment]
I saw big problems on Android when this widget is put inside of a react-native-navigation tab navigator.  Apparently it is because they both use `ViewPagerAndroid` and that object shouldn't be nested.  I was able to get it to work by setting `animationEnabled={false}` and `swipeEnabled={false}` on the tab navigator.
